# Generated by Django 5.1.3 on 2024-11-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_remove_match_team1_goals_remove_match_team2_goals_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='competitions',
            field=models.ManyToManyField(blank=True, related_name='teams', to='competitions.competition'),
        ),
    ]
