# Generated by Django 5.1.3 on 2024-11-27 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0006_remove_player_name_player_position_player_username"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="username",
        ),
        migrations.AddField(
            model_name="player",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player",
                to='users.CustomUser',
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="teams.team",
            ),
        ),
    ]
