# Generated by Django 5.1.3 on 2024-11-11 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team1_goals',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2_goals',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='competition',
        ),
        migrations.AddField(
            model_name='playerstats',
            name='match',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='competitions.match'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.competition'),
        ),
    ]
