# Generated by Django 5.1.3 on 2024-11-27 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "competitions",
            "0002_remove_match_team1_goals_remove_match_team2_goals_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionStandings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("standings_data", models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name="competition",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="competition",
            name="competition_type",
            field=models.CharField(
                choices=[("league", "League"), ("cup", "Cup")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="competitions.competition",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playerstats",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="competitions.match"
            ),
        ),
    ]
