# Generated by Django 5.1.3 on 2024-11-27 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0003_competitionstandings_competition_end_date_and_more"),
        ("teams", "0005_remove_playerapplication_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerstats",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teams.player"
            ),
        ),
        migrations.AddField(
            model_name="competitionstandings",
            name="competition",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standings",
                to="competitions.competition",
            ),
        ),
    ]
