# Generated by Django 5.1.3 on 2024-11-27 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0004_alter_playerstats_player_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="competitions.competition",
            ),
        ),
    ]
