# Generated by Django 5.1.3 on 2024-11-30 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0006_competition_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerstats",
            name="assists",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playerstats",
            name="goals",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playerstats",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_stats",
                to="competitions.match",
            ),
        ),
        migrations.AlterField(
            model_name="playerstats",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competition_stats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
