# Generated by Django 5.1.3 on 2024-11-30 13:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "competitions",
            "0007_alter_playerstats_assists_alter_playerstats_goals_and_more",
        ),
        ("teams", "0009_alter_transferrequest_player_alter_team_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playerstats",
            options={"verbose_name_plural": "Player Stats"},
        ),
        migrations.RenameField(
            model_name="match",
            old_name="team2_score",
            new_name="away_score",
        ),
        migrations.RenameField(
            model_name="match",
            old_name="team2",
            new_name="away_team",
        ),
        migrations.RenameField(
            model_name="match",
            old_name="team1_score",
            new_name="home_score",
        ),
        migrations.RenameField(
            model_name="match",
            old_name="team1",
            new_name="home_team",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="match",
            name="date",
        ),
        migrations.AddField(
            model_name="competition",
            name="current_round",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="competition",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="teams",
            field=models.ManyToManyField(related_name="competitions", to="teams.team"),
        ),
        migrations.AddField(
            model_name="competition",
            name="total_rounds",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="match",
            name="is_final",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="match_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="match",
            name="round_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="SCHEDULED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="playerstats",
            name="minutes_played",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstats",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_match_stats",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="competition_type",
            field=models.CharField(
                choices=[("LEAGUE", "League"), ("CUP", "Cup")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="competition",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="playerstats",
            name="assists",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playerstats",
            name="goals",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="playerstats",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_stats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="playerstats",
            unique_together={("player", "match")},
        ),
        migrations.DeleteModel(
            name="CompetitionStandings",
        ),
    ]
