# Generated by Django 4.2 on 2024-12-01 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0010_cachedteam_alter_playerapplication_team_and_more"),
        ("competitions", "0008_alter_playerstats_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedCompetition",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("competitions.competition",),
        ),
        migrations.CreateModel(
            name="CachedMatch",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("competitions.match",),
        ),
        migrations.AlterModelOptions(
            name="playerstats",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="playerstats",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="competition",
            name="current_round",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="total_rounds",
        ),
        migrations.RemoveField(
            model_name="match",
            name="away_score",
        ),
        migrations.RemoveField(
            model_name="match",
            name="home_score",
        ),
        migrations.RemoveField(
            model_name="match",
            name="is_final",
        ),
        migrations.RemoveField(
            model_name="match",
            name="round_number",
        ),
        migrations.AddField(
            model_name="match",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="competition",
            name="competition_type",
            field=models.CharField(
                choices=[
                    ("LEAGUE", "League"),
                    ("CUP", "Cup"),
                    ("TOURNAMENT", "Tournament"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="competition",
            name="teams",
            field=models.ManyToManyField(
                related_name="competitions", to="teams.cachedteam"
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="away_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away_matches",
                to="teams.cachedteam",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_matches",
                to="teams.cachedteam",
            ),
        ),
        migrations.AlterField(
            model_name="playerstats",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_stats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="playerstats",
            name="minutes_played",
        ),
        migrations.RemoveField(
            model_name="playerstats",
            name="red_cards",
        ),
        migrations.RemoveField(
            model_name="playerstats",
            name="team",
        ),
        migrations.AlterField(
            model_name="match",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="competitions.cachedcompetition",
            ),
        ),
        migrations.AlterField(
            model_name="playerstats",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_stats",
                to="competitions.cachedmatch",
            ),
        ),
    ]
