# Generated by Django 5.1.3 on 2024-11-11 21:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalevent',
            old_name='description',
            new_name='event_description',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='interviewee',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='date',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='event_title',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newspost',
            name='author',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
