# Generated by Django 5.1.3 on 2024-11-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_avatar_customuser_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_player",
            field=models.BooleanField(default=False),
        ),
    ]
